version: '3.3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contactlist
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
  
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - default
    env_file:
      - .env
    volumes:
      - .:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m celery -A contact_list_interview.celery worker --loglevel=info
    depends_on:
      - database
      - redis
      - app
    networks:
      - default
    env_file:
      - .env
    volumes:
      - .:/app

networks:
  default:
    name: contactlist
    driver: bridge