# Generated by Django 5.0 on 2023-12-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='user',
        ),
    ]
